# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/afe92867-a848-4020-9660-5c995a6d51c7";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/849A-B888";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/d029460c-1463-4ad2-812d-2ebf9ab668f9"; }];

  # Configure the governor used to regulate the frequence of the
  # available CPUs. By default, the kernel configures the
  # performance governor, although this may be overwritten in your
  # hardware-configuration.nix file.
  #
  # Often used values: "ondemand", "powersave", "performance"
  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
